@startuml
title SD - Registrer Vare
skinparam TitleFontSize 25
skinparam sequenceMessageAlign Center


actor medarbejder
participant ":RegisterProduct" as rp
participant ":ProductViewModel" as pvm
participant ":Product" as p
participant ":ProductRepository" as repo


autonumber 1


activate medarbejder


medarbejder -> rp : Åbner vareregistreringssystemet
activate rp


rp --> medarbejder : Viser registreringsformular


medarbejder -> rp : Indtaster Name, TimeReceived, ExpiringDate
medarbejder -> rp : Vælger FoodCategory
medarbejder -> rp : Indtaster Amount


opt Fortryd
    medarbejder -> rp : Klikker Tilbage
    rp --> medarbejder : Vender tilbage til hovedmenu
end


medarbejder -> rp : Klikker Registrér Vare
rp -> pvm : ExcuteCreateNewProduct()
activate pvm


pvm -> pvm : Validerer oplysninger


create p
pvm -> p : new Product(Name, Amount, TimeReceived, ExpiringDate)
activate p
note right of p : ProductNO genereres\nvia Guid.NewGuid()
p --> pvm : :Product
deactivate p


pvm -> repo : AddProduct(product)
activate repo
repo -> repo : Udfører AddProduct stored procedure
repo --> pvm : Vare gemt
deactivate repo


pvm --> rp : Vare oprettet
deactivate pvm


rp --> medarbejder : "Vare registreret"
deactivate rp


deactivate medarbejder


@enduml
